### ISSUE TITLE
Don't throw ArgumentTypeException for null values, always

### ISSUE THREAD

**Issue by iconara** [burtcorp/jmespath-java#23]
The type checking required by JMESPath is not made for performance. Throwing `ArgumentTypeException` when a `null` value is passed to a function that expects a string, for example, is very expensive, when in most cases you expect the result to be null anyway. We implemented this in [`burtpath`](https://github.com/burtcorp/burtpath) our ghetto-fork of `jmespath.rb`. Could we make something similar for `jmespath-java`? For example a flag to set to allow functions to be more lenient with `null` values. The `burtpath` implementation completely silenced errors when searching (but not when compiling), we might not want to be that extreme, I'm not sure.

**Comment by bjorne** [comment]
The flag actually made it into `JMESPath.rb` so I guess using the same semantics (unless considered too Ruby-idiomatic) would be a good idea.

See here for example: https://github.com/jmespath/jmespath.rb/blob/ac6e6ccf2c733ae2ede149c0b78e26b7d46f8d00/lib/jmespath/parser.rb#L32

**Comment by iconara** [comment]
I can think of two different versions of this:

* A flag that makes any search operation that normally would throw an exception return `null`. No errors are thrown from `Expression#search` at all. The search is not aborted though, it carries on so `max(foo) | {"max": @}` where `foo` is anything but the expected array of strings or array of numbers would result in `{max: null}` and not a type error – and `max(@, @) | {max: @}` would result in `{"max": null}` and not an arity error.
* A flag that makes functions behave be more lenient when checking types. When possible they would act reasonably when given `null` values, but they could still throw type errors when it wouldn't be possible to handle a `null` value. For example `max(foo)` where `foo` was `null` would behave like when `foo` was `[]`, i.e. return `null`. Passing the wrong number of arguments to a function would always be an error.

One motivation for bypassing the strict type checking is that it's a bit arbitrary. It's just functions that are strict, most other operations work fine with `null` values – `foo[]` when `foo` is `null` works fine, for example.

**Comment by iconara** [comment]
This has been released as [jmespath-0.3.0-SNAPSHOT](https://github.com/burtcorp/jmespath-java/releases/tag/jmespath-0.3.0-SNAPSHOT)
