### ISSUE TITLE
Bundle-SymbolicName header missing error when installing on AEM

### ISSUE THREAD

**Issue by gffny** [burtcorp/jmespath-java#28]
I'm implementing a feature in a project on AEM with AWS and the AWS libraries require the JMESPath library to be deployed to the container. The container requires that they bundle-SymbolicName been added to the header before it is deployable

**Comment by iconara** [comment]
I'm unsure as to what this means. From googling the terms I gather it has something to do with OSGi. The quickest way for this to happen is if you could submit a pull request with the necessary changes.
