### ISSUE TITLE
How to get back the URI of the current document in an expression?

### ISSUE THREAD

**Issue by gypapp** [burtcorp/jmespath-java#35]
It is rather a request for a new feature or at least for some guidance. 

Our system processes several hundreds and thousands of JSON response from various sources per day. There is an emerging demand to know the URI / URL / name of the currently processed document within the expression itself. (The driving force behind this request is that URL sometimes contains additional valuable information.) It could be something very similar to Saxon Xpath [document-uri()](https://www.saxonica.com/html/documentation/functions/fn/document-uri.html)

I've checked the documentation and have found that I could easily register new custom function to JacksonRuntime. It is awesome however I am a bit uncertain whether this would be the best approach since it would require my function to be stateful (ie. have a memory where the document url can be stored.)

Shall I create my custom runtime where I store the actual document URI and make my function stateless?

PS: I am using v0.2.1.

**Comment by iconara** [comment]
Stateful functions can work, but can be tricky to get right, especially in a multi-threaded environment. 

You could do something like this:

```java
public class DocumentUriFunction extends BaseFunction {
  private static String documentUri;

  public DocumentUriFunction() {
    super(/* there's actually no support for no-args functions, so you'd have to implement a new subclass of ArgumentConstraint and pass here */);
  }

  public void setDocumentUri(String documentUri) {
    this.documentUri = documentUri;
  }

  @Override
  protected <T> T callFunction(Adapter<T> runtime, List<FunctionArgument<T>> arguments) {
    return runtime.createString(documentUri);
  }
}

// ---

DocumentUriFunction documentUriFunction = new DocumentUriFunction();
FunctionRegistry defaultFunctions = FunctionRegistry.defaultRegistry();
FunctionRegistry customFunctions = defaultFunctions.extend(documentUriFunction);
RuntimeConfiguration configuration = new RuntimeConfiguration.Builder()
                                       .withFunctionRegistry(customFunctions)
                                       .build();
JmesPath<JsonNode> runtime = new JacksonRuntime(configuration);

// --

Expression<JsonNode> expression = jmespath.compile("something[?prop == document_uri()]");
documentUriFunction.setDocumentUri("foo.json");
JsonNode result = expression.search(input);
```

In a single threaded environment that would work fine, as long as you set the document URI before searching that's the value that will be returned by the function.

In a multi-threaded environment it's not that easy though. You would either have to keep one runtime per thread and ensure you never shared them between threads, or keep the document URI in a thread local (global variable essentially), or (not recommended) create a new runtime and recompile the expression for every invocation.

I guess you could implement your own runtime somehow – something I've been considering is to add a "search context", an object that would be passed around to every collaborator in a search. Such a context would be a good place to put a document URI. It's a pretty invasive change, though.

Did this help you at all? Did I understand what you were trying to do correctly?

**Comment by gypapp** [comment]
Yes, you got it right. Thanks for the code snippet, really appreciated. It is good to know that I was on the right track.

Since our environment is multithreaded that is why I want to be more cautious. I may give TLS a try since I do not see how I could add search context to a custom runtime.

Anyway, thanks a lot for your input.
