### ISSUE TITLE
jmespath-java  1.11.458 is not available

### ISSUE THREAD

**Issue by ssrangdal** [burtcorp/jmespath-java#38]
jmespath-java 1.11.458 is not available in below repo

https://repo1.maven.org/maven2/com/amazonaws/jmespath-java/

**Comment by slandelle** [comment]
@ssrangdal You're confusing this library and [the one from AWS](https://github.com/aws/aws-sdk-java/tree/master/jmespath-java).

**Comment by bittrance** [comment]
As noted, not relevant to this library.
