### ISSUE TITLE
Release v0.3?

### ISSUE THREAD

**Issue by naude-r** [burtcorp/jmespath-java#39]
good day,

would it be possible to make an official release of version 0.3.0? we are currently on 0.2.1, but would like to use RuntimeConfiguration, which was only introduced in 0.3.0-SNAPSHOT. 

it will be just fine if the SNAPSHOT version was pushed to maven central.

**Comment by slandelle** [comment]
The commit log show the [beginning of a release tentative](https://github.com/burtcorp/jmespath-java/commit/4e10c171c885e0438dcfa31020dbac7d8b57c593), but it looks like it was never completed.
Would it be possible to publish 0.3.0, please?

**Comment by iconara** [comment]
[0.3.0](https://github.com/burtcorp/jmespath-java/releases/tag/jmespath-0.3.0) has finally been released. Sorry for the wait folks.

**Comment by slandelle** [comment]
Awesome, thanks!
