### ISSUE TITLE
Comparing Field between different path Node. 

### ISSUE THREAD

**Issue by Emsys** [burtcorp/jmespath-java#54]
Hi guys , 

let's take example   the following structure : 

`{
  "X": {
    "instance": [
      {
        "id": "1",
        "groupId": "1"
      },
      {
        "id": "2",
        "groupId": "2"
      },
      {
        "id": "3",
        "groupId": "2"
      }
    ]
  },
  "Y": {
    "group": [
      {
        "isSecure": true,
        "name": "group1",
        "groupId": "1"
      },
      {
        "isSecure": false,
        "name": "group2",
        "groupId": "2"
      },
      {
        "isSecure": false,
        "name": "group1",
        "groupId": "3"
      }
    ]
  }
}`

I wish  inject a value of the current node into another node for example in this case to filter instance is the attached group have the field isSecure: to boolean .
that projection should be on X.instance   . if test Y.group[?groupId=='1' && isSecure]  this its correctly evaluated now  when i try to merge the expression like this : 
X.instance[?Y.group[?groupId==@.groupId && isSecure]] 
or
X.instance[?groupId==X.instance[?groupId==Y.group[?isSecure].groupId]]
 i will have not result 

i know in jsonpath  you can refer to  another node/path
this jsonpath equivalent work : $..instance[?(@.groupId IN $.Y.group[?(@.isSecure==true)].groupId)]
I do not know if it is an error on my part or a limitation
Thanks for your help

**Comment by iconara** [comment]
I'm not sure I understand what you're asking. Try it out on the sandbox on http://jmespath.org and if you can get it working there and not with this library update the issue. The library is fully compliant with the spec and the official test suite, but perhaps there's cases missing from the test suite.
