### ISSUE TITLE
Can't find the library

### ISSUE THREAD

**Issue by RushOT** [burtcorp/jmespath-java#59]
Failure to find `io.burt:jmespath:jar:0.5.0` in `https://repo.maven.apache.org/maven2` was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced

**Comment by slandelle** [comment]
`jmespath`is not a jar module but just the parent pom.
You have to pull one of the implementations instead, such as `jmespath-jackson`.

**Comment by RushOT** [comment]
Oh thank you
