### ISSUE TITLE
Standard API

### ISSUE THREAD

**Issue by iconara** [burtcorp/jmespath-java#6]
There's not really a standard API for JMESPath implementations, but most of the implementations look kind of the same, and it would be good if jmespath-java didn't stray too far from the existing APIs.

In Python there are two main APIs, there's the search API:

```python
result = jmespath.search('foo.bar', input)
```

and the compile API:

```
expression = jmespath.compile('foo.bar')
result = expression.search(input)
```

In Ruby there's only the search API (caching is done internally by default so there's no equivalent of the compile API):

```ruby
result = JMESPath.search('foo.bar', input)
```

In PHP this is the search API:

```php
$result = JmesPath\search($expression, $input);
```

and if you want to cache your expressions you create a runtime:

```php
$runtime = new JmesPath\AstRuntime();
$runtime('foo.bar', $input);
```

In JavaScript there's only the search API:

```javascript
jmespath.search(input, "foo.bar")
```

There's no API docs for the Go implementation as far as I can tell, but I think this is how the search API works:

```go
result, err := Search("foo.bar", input)
```

and the compile API:

```go
precompiled, err := Compile("foo.bar")
result, err := precompiled.Search(input)
```

Finally in Lua the search API looks like this:

```lua
local result = jmespath.search("foo.bar", input)
```

There's no compile API, but like in PHP you can create a runtime that will do caching:

```lua
local runtime = jmespath.runtime{cache = true}
runtime("foo.bar", input)
```

None of these would work very well in Java, especially not when there will be multiple backends, so the question is, how close can we get? How should the Java API work to feel familiar?

**Comment by iconara** [comment]
For reference, the current implementation of jmespath-java has no search API, and the equivalent to the compile API looks like this:

```java
Adapter<JsonNode> adapter = new JacksonAdapter();
Query query = Query.fromString(adapter, "foo.bar");
JsonNode result query.evaluate(adapter, input);
```

**Comment by iconara** [comment]
I don't care much for the search API, I don't really see the use for it, if you really don't want to cache your compiled expressions you can write that API yourself easily enough.

If we changed things around we could have a compile API that looked something like this:

```java
Runtime<JsonNode> jmespath = new JacksonRuntime();
Query<JsonNode> query = jmespath.compile("foo.bar");
JsonNode result = query.search(input);
```

That feels pretty close to the other implementations. The difference from what we have now is that the adapter would be renamed "runtime" (does that matter? should we keep "adapter"?), and the query object would keep a reference to the adapter/runtime. That's probably a good idea anyway (even though I've tried to keep `Query` adapter-agostic so far I'm beginning to doubt the usefulness of that).

**Comment by grddev** [comment]
> That feels pretty close to the other implementations. The difference from what we have now is that the adapter would be renamed "runtime" (does that matter? should we keep "adapter"?), and the query object would keep a reference to the adapter/runtime. That's probably a good idea anyway (even though I've tried to keep Query adapter-agostic so far I'm beginning to doubt the usefulness of that).

I like it better than the current version. I'm not sure it is the intention of the name "runtime" in the other projects, but here I think it actually makes more sense than adapter. The way I see it, it is a runtime that provides a set of primitives upon which the query/search functionality is built. The fact that some of those primitives adapt seems like a not so important detail to me.

I'm not sure why this would require `Query` to know about the internals of the runtime, but the fact that you cannot supply different adaptors/runtimes to different searches only seems like an advantage to me. With the proposed interface, nothing prevents the `JacksonRuntime` from actually returning a `Query` subclass (assuming the `Query` class is not final).

**Comment by iconara** [comment]
It wouldn't require the `Query` class to know about the internals of the runtime, what I meant was that `Query` would keep a reference to a runtime. I think we are in agreement besides that point of confusion.
