### ISSUE TITLE
Feature request: Clone a FunctionRegistry with exclusions

### ISSUE THREAD

**Issue by gibson042** [burtcorp/jmespath-java#61]
The FunctionRegistry `extend` method can be used to create a new registry that has all the functions of the context registry plus provided additions. But it should also be possible to create a new registry that has all the functions of the context _except_ provided exclusions. This can be used to filter out e.g. functions with known non-linear performance:
```java
FunctionRegistry defaultRegistry = FunctionRegistry.defaultRegistry();
FunctionRegistry saferDefaultRegistry = defaultRegistry.extendWithout("merge", "sort", "sort_by");
```

**Comment by iconara** [comment]
We have decided to deprecate this project and put the repo in archive mode.
