### ISSUE TITLE
Parser crashes with kebab case identifiers

### ISSUE THREAD

**Issue by bumblebeen** [burtcorp/jmespath-java#74]
I have a json below with a query of "item.foo-bar"

```json
{
    "item": {"foo-bar": "baz"}
}
```

If I run something like `compile("item.foo-bar")`
The parser crashes with this error. 

```
Unable to compile expression "item.foo-bar": syntax error token recognition error at: '-b' at position 8, syntax error extraneous input 'ar' expecting <EOF> at position 10

io.burt.jmespath.parser.ParseException: Unable to compile expression "item.foo-bar": syntax error token recognition error at: '-b' at position 8, syntax error extraneous input 'ar' expecting <EOF> at position 10
```

I played around jmespath and I believe it should be supported with the java-client

![jmespath example](https://user-images.githubusercontent.com/8120302/206276228-a785354d-578a-4231-b65b-85c654ee0ea9.png)

**Comment by chadselph** [comment]
Not sure if you already found this but you should be able to use `item."foo-bar"` as the expression.

**Comment by iconara** [comment]
We have decided to deprecate this project and put the repo in archive mode.
