### ISSUE TITLE
JEP 18

### ISSUE THREAD

**Issue by spoerri** [burtcorp/jmespath-java#76]
Are there any plans to support [JEP 18](https://github.com/jmespath/jmespath.jep/blob/main/proposals/0018-lexical-scope.md)?

**Comment by iconara** [comment]
No, sorry. This library is not very actively developed and that looks like a significant amount of work. If someone contributed it I would not be against merging (but I think there may be one or two other things that need to be added to get up to date with where JMESPath is these days first).
