### ISSUE TITLE
Comparable class support in compareObjects

### ISSUE THREAD

**Issue by headlessButSmart** [burtcorp/jmespath-java#80]
It would be great if ComparisonNode supports comparison of non-numbers (i.e. String values).

A comparison like 'a'<'b' returns True on jmespath.org with the JS implementation while jmespath-java returns null since compareObjects in ComparisonNode returns null for LessThanNode and similar implementations.

**Comment by iconara** [comment]
We have decided to deprecate this project and put the repo in archive mode.
