### ISSUE TITLE
Continuous compliance testing

### ISSUE THREAD

**Issue by iconara** [burtcorp/jmespath-java#9]
There's currently no way to run the compliance tests. Ideally they should be run with every Travis job. Either the (now kind of defunct) compliance tool needs to be updated or a `jp` tool added so that the compliance suite's test tool can be used.

It would be great if the compliance tests could be used to generate JUnit tests on the fly, but I'm not sure if that is possible. I'm thinking something that reads the compliance JSON files and runs each as a test in a JUnit harness so that they can be run by Maven and that we could get standardized reports.

Until we feel that 100% compliance is achievable it should be run as an allowed-failure-job in Travis.

**Comment by iconara** [comment]
Looks like a custom JUnit runner could do the job, actually.

**Comment by grddev** [comment]
Fixed by #11, right?

**Comment by iconara** [comment]
Yes!
